export const SET_WEATHER = 'SET_WEATHER';
export const FETCH_WEATHER_LOADING = 'FETCH_WEATHER_LOADING',
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS',
export const FETCH_WEATHER_FAIL = "FETCH_WEATHER_FAIL";

export const SET_LOCATION = 'SET_LOCATION';
export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const FETCH_LOCATION_LOADING = 'FETCH_LOCATION_LOADING',
export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS',
export const FETCH_LOCATION_FAIL = "FETCH_LOCATION_FAIL";
